#!/bin/bash

# ./local-settings 文件默认配置，请确保存在这个文件并修改相关配置
LOCAL_ROOT="/var/hosts/cd/very/www/"
JAVA_BIN="/usr/local/java/bin/java"
MD5_BIN="/sbin/md5 -q"
PHP_BIN="/usr/local/bin/php"
PATCH_BIN="/usr/bin/patch"
COMPRESSOR_JAR="/usr/local/lib/java/yuicompressor-2.4.2.jar"
PASSWORD_FILE="/Users/xdanger/.rsync.passwd/delia"

# 读取本地环境配置
S="`pwd`/local-settings"
if test ! -f $S; then
	echo "没有读取到本地配置文件 local-settings"
fi
. $S

# 产品环境配置
REMOTE_HOSTS="httpd-2.verycd.com coral.xdanger.com httpd-32.verycd.com httpd-26.verycd.com httpd-27.verycd.com"
JS_SRC="app home"
JS_CHARSET="gb2312"

U="n"
# ./release ok
if test "$1" == "ok"; then
    U=""
fi
# remote branch
R="www"
if test "$2" == "beta"; then
    R="beta"
fi

cd $LOCAL_ROOT
echo "=========正在压缩JS========="
for js in $JS_SRC; do
    echo "------$js------"
		src="i/$js.src.js"
		dst="i/$js.js"
		tmp="i/$js.js.tmp"
    $JAVA_BIN -jar $COMPRESSOR_JAR --charset 'gb2312' -o $tmp $src || exit 1
		if test "`$MD5_BIN $dst`" == "`$MD5_BIN $tmp`"; then
			rm $tmp
		else
			mv $tmp $dst
		fi
done

echo "=========正在生成alpha-sites.html========="

for f in html js; do
	dst="i/alpha-sites.$f"
	tmp="i/alpha-sites.$f.tmp"
	$PHP_BIN i/alpha-sites.php $f > $tmp || exit 1
	if test "`$MD5_BIN $dst`" == "`$MD5_BIN $tmp`"; then
		rm $tmp
	else
		mv $tmp $dst
	fi
done

src="beta.patch"
dst="beta.html"
tmp="beta.html.tmp"
if test -f "$src"; then
    echo "=========正在生成beta.html========="
    $PATCH_BIN index.html -o $tmp < $src || exit 1
    if test "`$MD5_BIN $dst`" == "`$MD5_BIN $tmp`"; then
        rm $tmp
    else
        mv $tmp $dst
    fi
fi

echo "=========正在上传========="
for h in $REMOTE_HOSTS; do
    rsync -ruvz$U \
        --delete-after \
        --exclude /release \
        --exclude /local-settings \
        --exclude /nbproject \
        --exclude /beta.patch \
        --exclude .git/ \
        --exclude .svn/ \
        --exclude .gitignore \
        --exclude .DS_Store \
        --exclude api/weather/details/ \
        --password-file $PASSWORD_FILE \
      $LOCAL_ROOT delia@$h::7999/$R/
done
