document.writeln("<table width=96%  border=0 cellspacing=0 cellpadding=0>");
document.writeln("<tr>");		  
document.writeln("<td colspan=2>");
document.writeln("<table width=100%  border=0 cellspacing=0 cellpadding=0>");
document.writeln("<tr>");
document.writeln("<td width=25 align=center><img src=../hudonghd/images/dot_01.gif width=20 height=21 border=0></td>");  
document.writeln("<td class=f14>相关网址大全</td>"); 
document.writeln("</tr>"); 
document.writeln("<tr>");
document.writeln("<td height=3 colspan=2 bgcolor=#4BCB66></td>");
document.writeln("</tr>");
document.writeln("</table></td>");
document.writeln("</tr>");
document.writeln("<tr>"); 
document.writeln("<td width=300 align=center bgcolor=#F7FDF6><table width=150  border=0 align=center cellpadding=1 cellspacing=0>");
document.writeln("<tr>"); 
document.writeln("<td height=1 colspan=2 background=../hudonghd/images/dot_05.gif></td>"); 
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td><img src=../hudonghd/images/dot_02.gif width=8 height=20></td>");
document.writeln("<td class=f9><a href=02tieba.htm class=mm>百度热门贴吧列表</a></td>");
document.writeln("</tr>");
document.writeln("<tr>"); 
document.writeln("<td height=1 colspan=2 background=../hudonghd/images/dot_05.gif></td>"); 
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td><img src=../hudonghd/images/dot_02.gif width=8 height=20></td>");
document.writeln("<td class=f9><a href=18shipinjc.htm class=mm>视频教程大全</a></td>");
document.writeln("</tr>");
document.writeln("<tr>"); 
document.writeln("<td height=1 colspan=2 background=../hudonghd/images/dot_05.gif></td>"); 
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td><img src=../hudonghd/images/dot_02.gif width=8 height=20></td>");
document.writeln("<td class=f9><a href=23citiao.htm class=mm>百科精彩词条大全</a></td>");
document.writeln("</tr>");
document.writeln("<tr>"); 
document.writeln("<td height=1 colspan=2 background=../hudonghd/images/dot_05.gif></td>"); 
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td><img src=../hudonghd/images/dot_02.gif width=8 height=20></td>");
document.writeln("<td class=f9><a href=../caipu.htm class=mm>家常菜大全</a></td>");
document.writeln("</tr>");
document.writeln("</table></td>");
document.writeln("</tr></table>");